<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <!-- https://github.com/gircore/gir.core/releases/tag/0.8.0-preview.1 -->
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <SelfContained>true</SelfContained>
        <PublishTrimmed>false</PublishTrimmed>
		<!-- Workaround for Rider bug https://youtrack.jetbrains.com/issue/RIDER-56918/Cannot-start-debugging-net5-project-on-Linux-when-using-PublishSingleFile-in-.proj-file -->
		<PublishSingleFile  Condition="'$(Configuration)' == 'Release'">true</PublishSingleFile>
		<AssemblyName>webcamcontrol</AssemblyName>
		<Version>1.2.1</Version>
		<IncludeSourceRevisionInInformationalVersion>true</IncludeSourceRevisionInInformationalVersion>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.6" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.6" />
      <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.6" />
      <PackageReference Include="Microsoft.NET.ILLink.Tasks" Version="10.0.6" />
    </ItemGroup>


    <Target Name="BlueprintBuild" BeforeTargets="BeforeCompile">
        <!-- Build Blueprints -->
		<Message Text="Running blueprint-compiler" Importance="high" />
        <Exec Command="blueprint-compiler batch-compile $(MSBuildProjectDirectory)/obj/blueprints/ $(MSBuildProjectDirectory) $(MSBuildProjectDirectory)/*.blp $(MSBuildProjectDirectory)/Widgets/*.blp "/>
    </Target>
	
	<Target Name="CompileGLibResources" BeforeTargets="BeforeCompile">
		<!-- Compile resources into gresource file. Required for icon in about dialog -->
		<Exec Command="glib-compile-resources $(MSBuildProjectDirectory)/resources.xml --target=$(MSBuildProjectDirectory)/webcamcontrol.gresource --sourcedir=." />
	</Target>


    <Target Name="ExtraCleanup" AfterTargets="Clean">
        <!-- Remove obj folder -->
        <RemoveDir Directories="$(BaseIntermediateOutputPath)"/>
        <!-- Remove bin folder -->
        <RemoveDir Directories="$(BaseOutputPath)"/>

        <!-- Remove compiled blueprints -->
        <RemoveDir Directories="$(MSBuildProjectDirectory)/obj/blueprints"/>
    </Target>

    <!-- Add the blueprints as a resource -->
    <ItemGroup>
        <None Remove="obj\blueprints\*.ui"/>
        <EmbeddedResource Include="obj\blueprints\**\*.ui">
            <LogicalName>%(Filename)%(Extension)</LogicalName>
        </EmbeddedResource>
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\..\..\gir.core\src\Integrations\GObject-2.0.Integration\GObject-2.0.Integration.csproj" 
						OutputItemType="Analyzer"
                        ReferenceOutputAssembly="false" />
      <ProjectReference Include="..\..\..\gir.core\src\Integrations\Gtk-4.0.Integration\Gtk-4.0.Integration.csproj"
						OutputItemType="Analyzer"
                        ReferenceOutputAssembly="false" />
      <ProjectReference Include="..\..\..\gir.core\src\Libs\Adw-1\Adw-1.csproj" />
      <ProjectReference Include="..\..\..\gir.core\src\Libs\Gtk-4.0\Gtk-4.0.csproj" />
      <ProjectReference Include="..\WebCamControl.Core\WebCamControl.Core.csproj" />
    </ItemGroup>
    <ItemGroup>
      <None Remove="webcamcontrol.gresource" />
      <EmbeddedResource Include="webcamcontrol.gresource" />
    </ItemGroup>

</Project>
